language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - sudo apt-get install -qq doxygen graphviz
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cmake .
- cmake --build .
- cmake --build . --target package
- doxygen Doxyfile
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uyurymylnikov:$BINTRAY_API_KEY "https://api.bintray.com/content/yurymylnikov/OTUS/DZ04_print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  - provider: pages
    skip-cleanup: true
    local_dir: doc
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master